@extends('layouts.app')
@section('title','About Us — India Uncaged')
@section('content')
@php($site=app(\App\Support\SiteSettings::class))
<section class="about-hero"><div><p class="eyebrow">ABOUT INDIA UNCAGED</p><h1>{{ $site::get('about_headline','Travel deeper into the wild.') }}</h1><p>{{ $site::get('about_intro','Wildlife journeys shaped by curiosity, field knowledge and a deep respect for the places we visit.') }}</p></div></section>
<section class="about-story"><div class="about-story__label"><p class="eyebrow">OUR STORY</p></div><div class="about-story__content">{!! nl2br(e($site::get('about_story',''))) !!}</div></section>
<section class="about-approach"><div><p class="eyebrow">OUR APPROACH</p><h2>Experience first. Photograph second.</h2></div><div><p>{{ $site::get('about_approach','We believe wildlife travel should create meaningful time in the field — with patience, context and respect for animals, habitats and local communities.') }}</p></div></section>
<section class="about-responsible"><p class="eyebrow">RESPONSIBLE WILDLIFE TOURISM</p><h2>{{ $site::get('about_responsible_headline','Leave the wild as wild as we found it.') }}</h2><p>{{ $site::get('about_responsible_text','Responsible travel is part of every journey we build. We prioritise ethical wildlife viewing, respect for local rules and habitats, and thoughtful interaction with communities.') }}</p></section>
<section class="about-team"><div class="section-heading"><p class="eyebrow">THE TEAM</p><h2>{{ $site::get('about_team_headline','People who spend time in the field.') }}</h2></div><div class="team-grid">@foreach(range(1,3) as $i) @if($site::get('team_'.$i.'_name'))<article><div class="team-photo" style="{{ $site::get('team_'.$i.'_image') ? "background-image:url('".e($site::get('team_'.$i.'_image'))."')" : '' }}"></div><p class="eyebrow">{{ $site::get('team_'.$i.'_role') }}</p><h3>{{ $site::get('team_'.$i.'_name') }}</h3><p>{{ $site::get('team_'.$i.'_bio') }}</p></article>@endif @endforeach</div></section>
<section class="about-instagram"><div><p class="eyebrow">FOLLOW THE JOURNEY</p><h2>{{ $site::get('instagram_handle','@india_uncaged') }}</h2><a class="button button--ghost" href="{{ $site::get('instagram_url','https://instagram.com/india_uncaged') }}" target="_blank" rel="noopener">FOLLOW @INDIA_UNCAGED</a></div>@if($site::get('instagram_embed_code'))<div class="instagram-embed">{!! $site::get('instagram_embed_code') !!}</div>@else<div class="instagram-embed instagram-embed--empty"><p>Follow along for photographs, field notes and upcoming journeys.</p></div>@endif</section>
@endsection