@extends('layouts.app')
@section('title', 'India Uncaged — Wildlife Expeditions')
@section('content')
@php($site=app(\App\Support\SiteSettings::class))
<section class="home-hero" style="{{ $site::get('hero_poster') ? "background-image:url('".e($site::get('hero_poster'))."')" : '' }}">
 @if($site::get('hero_video'))<video class="home-hero__video" autoplay muted loop playsinline poster="{{ $site::get('hero_poster') }}"><source src="{{ $site::get('hero_video') }}"></video>@endif
 <div class="home-hero__overlay"></div><div class="home-hero__copy"><p class="eyebrow">INDIA UNCAGED</p><h1>{{ $site::get('hero_headline','Where the wild still writes the story.') }}</h1><p>{{ $site::get('hero_subheadline','Premium wildlife journeys shaped by field knowledge, photography and responsible travel.') }}</p><div class="hero-actions"><a class="button button--primary" href="{{ $site::get('hero_primary_url',route('plan')) }}">{{ $site::get('hero_primary_label','PLAN YOUR JOURNEY') }}</a>@if($site::get('hero_secondary_label'))<a class="button button--ghost" href="{{ $site::get('hero_secondary_url',route('tours')) }}">{{ $site::get('hero_secondary_label') }}</a>@endif</div></div>
</section>

<section class="home-section"><div class="section-heading"><p class="eyebrow">SHOT IN THE WILD</p><h2>A glimpse from the field.</h2></div><div class="home-gallery">@forelse($gallery as $image)<a href="{{ route('gallery') }}" class="home-gallery__item"><img src="{{ $image->image_path }}" alt="{{ $image->caption ?: 'India Uncaged wildlife photograph' }}" loading="lazy"></a>@empty<div class="empty-state"><h3>Photography from the field will appear here.</h3><p>Add featured gallery images from the admin panel.</p></div>@endforelse</div></section>

<section class="home-section home-section--dark"><div class="section-heading"><p class="eyebrow">UPCOMING IN THE WILD</p><h2>Our next journeys.</h2><a href="{{ route('tours') }}">VIEW ALL TOURS →</a></div><div class="tour-grid">@foreach($featured->merge($rest)->take(6) as $date)<a class="home-tour-card" href="{{ route('tour',$date->tour) }}"><div class="home-tour-card__image" style="{{ $date->tour->hero_image ? "background-image:url('".e($date->tour->hero_image)."')" : '' }}"></div><div><p class="eyebrow">{{ $date->tour->destination->name }}</p><h3>{{ $date->tour->name }}</h3><p>{{ $date->start_date->format('d M Y') }} — {{ $date->end_date->format('d M Y') }}</p></div></a>@endforeach@if(!$featured->count()&&!$rest->count())<div class="empty-state empty-state--dark"><h3>New expeditions are being prepared.</h3><p>Check back soon or plan a private journey with us.</p></div>@endif</div></section>

<section class="home-section"><div class="section-heading"><p class="eyebrow">WHERE THE WILD TAKES YOU</p><h2>Explore our destinations.</h2><a href="{{ route('destinations') }}">VIEW DESTINATIONS →</a></div><div class="destination-grid">@forelse($destinations as $destination)<a class="destination-card" href="{{ route('destination',$destination) }}"><div class="destination-card__image" style="{{ $destination->hero_image ? "background-image:url('".e($destination->hero_image)."')" : '' }}"></div><div><p class="eyebrow">{{ $destination->state_region }}</p><h3>{{ $destination->name }}</h3><p>{{ $destination->tagline }}</p></div></a>@empty<div class="empty-state"><h3>Your featured destinations will appear here.</h3><p>Mark destinations as featured in the admin panel.</p></div>@endforelse</div></section>

<section class="home-section why-section"><div class="section-heading"><p class="eyebrow">WHY INDIA UNCAGED</p><h2>Travel deeper. See more.</h2></div><div class="pillars"><div><span>01</span><h3>Field Knowledge</h3><p>Journeys shaped by real field experience and an understanding of wildlife behaviour.</p></div><div><span>02</span><h3>Photography</h3><p>Thoughtful itineraries built for observing, experiencing and creating in the wild.</p></div><div><span>03</span><h3>Small Groups</h3><p>More time in the field, less time moving through crowds.</p></div><div><span>04</span><h3>Responsible Travel</h3><p>Wildlife experiences designed with respect for habitats, communities and animals.</p></div></div></section>

<section class="home-section"><div class="section-heading"><p class="eyebrow">JOURNAL</p><h2>Notes from the field.</h2><a href="{{ route('journal') }}">READ THE JOURNAL →</a></div><div class="journal-grid">@forelse($journal as $article)<a class="journal-card" href="{{ route('journal.show',$article) }}"><div class="journal-card__image" style="{{ $article->cover_image ? "background-image:url('".e($article->cover_image)."')" : '' }}"></div><div><p class="eyebrow">{{ $article->category }}</p><h3>{{ $article->title }}</h3><p>{{ $article->excerpt }}</p></div></a>@empty<div class="empty-state"><h3>Field notes are coming.</h3><p>Published journal articles will appear here.</p></div>@endforelse</div></section>

<section class="home-cta"><p class="eyebrow">YOUR NEXT WILD JOURNEY</p><h2>Ready to enter the wild?</h2><p>Tell us where you want to go, what you want to see and how you want to experience it.</p><a class="button button--primary" href="{{ route('plan') }}">PLAN YOUR JOURNEY</a></section>
@endsection