@extends('layouts.app')
@section('content')
<section class="admin-page"><div class="admin-header"><div><p class="eyebrow">CMS / Gallery</p><h1>{{ $image->exists ? 'Edit image' : 'New image' }}</h1></div><a class="button" href="{{ route('admin.gallery.index') }}">Back</a></div>
@if(session('success'))<div class="notice">{{ session('success') }}</div>@endif
@if($errors->any())<div class="notice notice--error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $image->exists ? route('admin.gallery.update',$image) : route('admin.gallery.store') }}" class="admin-form">@csrf @if($image->exists) @method('PUT') @endif
<div class="form-section"><p class="eyebrow">Image</p><label>Image path / URL<input name="image_path" value="{{ old('image_path',$image->image_path) }}" required></label><div class="form-grid form-grid--2"><label>Category<select name="category">@foreach(['tour_experiences','bts','fauna','herping','birds','landscapes'] as $category)<option value="{{ $category }}" @selected(old('category',$image->category)===$category)>{{ str($category)->replace('_',' ')->title() }}</option>@endforeach</select></label><label>Photographer<input name="photographer" value="{{ old('photographer',$image->photographer) }}"></label><label>Location<input name="location" value="{{ old('location',$image->location) }}"></label><label>Date taken<input type="date" name="taken_on" value="{{ old('taken_on',$image->taken_on?->format('Y-m-d')) }}"></label><label>Width<input type="number" min="1" name="width" value="{{ old('width',$image->width) }}"></label><label>Height<input type="number" min="1" name="height" value="{{ old('height',$image->height) }}"></label></div><label>Caption<textarea name="caption" rows="4">{{ old('caption',$image->caption) }}</textarea></label></div>
<div class="form-section"><p class="eyebrow">Context</p><div class="form-grid form-grid--2"><label>Destination<select name="destination_id"><option value="">None</option>@foreach($destinations as $destination)<option value="{{ $destination->id }}" @selected(old('destination_id',$image->destination_id)==$destination->id)>{{ $destination->name }}</option>@endforeach</select></label><label>Tour<select name="tour_id"><option value="">None</option>@foreach($tours as $tour)<option value="{{ $tour->id }}" @selected(old('tour_id',$image->tour_id)==$tour->id)>{{ $tour->name }}</option>@endforeach</select></label></div></div>
<div class="form-section form-section--inline"><label class="check"><input type="checkbox" name="featured" value="1" @checked(old('featured',$image->featured))> Featured</label><label class="check"><input type="checkbox" name="published" value="1" @checked(old('published',$image->published))> Published</label></div>
<div class="admin-actions"><button class="button button--primary">Save image</button></div></form>
@if($image->exists)<form method="POST" action="{{ route('admin.gallery.destroy',$image) }}" class="danger-form">@csrf @method('DELETE')<button class="button button--danger" onclick="return confirm('Delete this image?')">Delete image</button></form>@endif
</section>
@endsection